"use client";
import { useState, useEffect, useRef, useCallback } from "react";
const C={base:"#080808",deep:"#050505",surface:"#0f0f0f",panel:"rgba(255,255,255,0.03)",border:"rgba(255,255,255,0.07)",red:"#d42020",redDeep:"#8a0e0e",redGlow:"rgba(212,32,32,0.14)",green:"#1a7a1a",greenBright:"#22c55e",greenGlow:"rgba(34,197,94,0.12)",cream:"#f0ece4",muted:"rgba(255,255,255,0.48)",dim:"rgba(255,255,255,0.22)",border2:"rgba(255,255,255,0.06)",blue:"#1e6bb8",pink:"#d94090",yellow:"#c8a020",white:"#e8e8e8"};
const F={serif:"'Cormorant Garamond','Playfair Display',Georgia,serif",sans:"'DM Sans','Inter',system-ui,sans-serif"};
function useInView(t=0.1){const ref=useRef<HTMLDivElement>(null);const[v,setV]=useState(false);useEffect(()=>{const el=ref.current;if(!el)return;const o=new IntersectionObserver(([e])=>{if(e.isIntersecting)setV(true)},{threshold:t});o.observe(el);return()=>o.disconnect()},[t]);return[ref,v] as const}
function Reveal({children,d=0}:{children:React.ReactNode;d?:number}){const[ref,v]=useInView();return<div ref={ref} style={{transform:v?"translateY(0)":"translateY(32px)",opacity:v?1:0,transition:`all 0.9s cubic-bezier(0.16,1,0.3,1) ${d}s`}}>{children}</div>}
const Grain=({o=0.04}:{o?:number})=>(<div style={{position:"absolute",inset:0,opacity:o,pointerEvents:"none",backgroundImage:`url("data:image/svg+xml,%3Csvg viewBox='0 0 512 512' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence baseFrequency='0.65' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`}}/>);

function VideoPortal({onComplete}:{onComplete:()=>void}){const videoRef=useRef<HTMLVideoElement>(null);const[phase,setPhase]=useState<"playing"|"dissolving"|"done">("playing");const[progress,setProgress]=useState(0);useEffect(()=>{const vid=videoRef.current;if(!vid)return;const htu=()=>{if(vid.duration){const p=vid.currentTime/vid.duration;setProgress(p);if(p>=0.75&&phase==="playing")setPhase("dissolving")}};const he=()=>{setPhase("done");setTimeout(onComplete,600)};vid.addEventListener("timeupdate",htu);vid.addEventListener("ended",he);vid.play().catch(()=>{setPhase("done");setTimeout(onComplete,300)});return()=>{vid.removeEventListener("timeupdate",htu);vid.removeEventListener("ended",he)}},[onComplete,phase]);const handleSkip=useCallback(()=>{setPhase("done");setTimeout(onComplete,400)},[onComplete]);if(phase==="done")return null;return(
<div onClick={handleSkip} style={{position:"fixed",inset:0,zIndex:9999,background:"#050505",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",opacity:phase==="dissolving"?0:1,transition:"opacity 1.6s cubic-bezier(0.16,1,0.3,1)"}}>
<video ref={videoRef} src="/videos/portal.mp4" muted playsInline preload="auto" style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover",transform:phase==="dissolving"?"scale(1.08)":"scale(1)",transition:"transform 1.8s cubic-bezier(0.16,1,0.3,1)"}}/>
<div style={{position:"absolute",inset:0,background:"radial-gradient(ellipse at center,transparent 30%,rgba(5,5,5,0.6) 80%,rgba(5,5,5,0.95) 100%)",pointerEvents:"none"}}/>
<div style={{position:"relative",zIndex:2,textAlign:"center",opacity:progress>0.1?1:0,transform:progress>0.1?"translateY(0)":"translateY(20px)",transition:"all 1.2s cubic-bezier(0.16,1,0.3,1)"}}>
<div style={{fontFamily:F.sans,fontSize:"8px",letterSpacing:"0.6em",textTransform:"uppercase",color:C.red,marginBottom:"16px",textShadow:"0 0 30px rgba(212,32,32,0.4)"}}>Premium Energy</div>
<div style={{fontFamily:F.sans,fontSize:"clamp(48px,12vw,160px)",fontWeight:900,lineHeight:0.85,letterSpacing:"-0.04em",color:C.cream,textShadow:"0 0 60px rgba(0,0,0,0.8)"}}>PRONTO</div></div>
<div style={{position:"absolute",bottom:"48px",left:"50%",transform:"translateX(-50%)",zIndex:3,display:"flex",flexDirection:"column",alignItems:"center",gap:"16px"}}>
<div style={{width:"120px",height:"1px",background:"rgba(255,255,255,0.12)",overflow:"hidden",borderRadius:"1px"}}><div style={{width:`${progress*100}%`,height:"100%",background:`linear-gradient(90deg,${C.red},${C.greenBright})`,transition:"width 0.3s ease"}}/></div>
<div style={{fontFamily:F.sans,fontSize:"8px",letterSpacing:"0.4em",textTransform:"uppercase",color:"rgba(255,255,255,0.25)"}}>Tap to Enter</div></div>
<Grain o={0.05}/></div>)}

function Nav({visible}:{visible:boolean}){const[s,setS]=useState(false);useEffect(()=>{const h=()=>setS(window.scrollY>60);window.addEventListener("scroll",h,{passive:true});return()=>window.removeEventListener("scroll",h)},[]);return(
<nav style={{position:"fixed",top:0,left:0,right:0,zIndex:100,padding:s?"14px clamp(24px,4vw,64px)":"26px clamp(24px,4vw,64px)",display:"flex",justifyContent:"space-between",alignItems:"center",background:s?"rgba(8,8,8,0.96)":"transparent",backdropFilter:s?"blur(28px)":"none",borderBottom:s?`1px solid ${C.border}`:"none",transition:"all 0.5s cubic-bezier(0.16,1,0.3,1)",opacity:visible?1:0,transform:visible?"translateY(0)":"translateY(-20px)"}}>
<div style={{display:"flex",alignItems:"center",gap:"10px"}}><div style={{width:"8px",height:"28px",background:`linear-gradient(180deg,${C.red},${C.green})`,borderRadius:"4px"}}/><div><div style={{fontFamily:F.sans,fontSize:"7px",letterSpacing:"0.5em",textTransform:"uppercase",color:C.red,marginBottom:"2px"}}>Premium Energy</div><span style={{fontFamily:F.sans,fontSize:"18px",fontWeight:800,color:C.cream,letterSpacing:"0.06em"}}>PRONTO</span></div></div>
<div style={{display:"flex",gap:"clamp(14px,2.5vw,36px)",alignItems:"center"}}>
{["Flavors","Science","Lifestyle","Partners"].map(n=>(<a key={n} href={`#${n.toLowerCase()}`} style={{fontFamily:F.sans,fontSize:"10px",fontWeight:500,letterSpacing:"0.22em",textTransform:"uppercase",color:C.muted,textDecoration:"none",transition:"color 0.3s"}} onMouseEnter={e=>(e.target as HTMLElement).style.color=C.cream} onMouseLeave={e=>(e.target as HTMLElement).style.color=C.muted}>{n}</a>))}
<button style={{fontFamily:F.sans,fontSize:"10px",fontWeight:700,letterSpacing:"0.14em",textTransform:"uppercase",color:C.cream,background:`linear-gradient(135deg,${C.red},${C.redDeep})`,border:"none",padding:"10px 28px",cursor:"pointer",transition:"all 0.3s"}} onMouseEnter={e=>e.currentTarget.style.transform="translateY(-2px)"} onMouseLeave={e=>e.currentTarget.style.transform="translateY(0)"}>Get Pronto</button></div></nav>)}

function Hero({siteReady}:{siteReady:boolean}){const[loaded,setLoaded]=useState(false);useEffect(()=>{if(siteReady)setTimeout(()=>setLoaded(true),200)},[siteReady]);return(
<section style={{minHeight:"100vh",position:"relative",overflow:"hidden",background:C.base,display:"flex",flexDirection:"column"}}>
<Grain o={0.04}/>
<div style={{position:"absolute",inset:0}}><img src="/images/products/all-flavors-elemental.png" alt="Pronto Energy All 5 Flavors" style={{width:"100%",height:"100%",objectFit:"cover",objectPosition:"center 30%",opacity:loaded?0.6:0,transition:"opacity 1.4s cubic-bezier(0.16,1,0.3,1) 0.2s"}}/><div style={{position:"absolute",inset:0,background:`linear-gradient(180deg,rgba(8,8,8,0.3) 0%,rgba(8,8,8,0.5) 40%,rgba(8,8,8,0.92) 75%,${C.base} 100%)`}}/></div>
<div style={{position:"relative",zIndex:2,flex:1,display:"flex",flexDirection:"column",justifyContent:"flex-end",padding:"0 clamp(32px,6vw,96px) 96px",maxWidth:"1400px",margin:"0 auto",width:"100%"}}>
<div style={{fontFamily:F.sans,fontSize:"9px",letterSpacing:"0.55em",textTransform:"uppercase",color:C.red,opacity:loaded?1:0,transition:"opacity 0.9s ease 0.3s",marginBottom:"20px"}}>5 Bold Flavors · Zero Sugar · No Crash</div>
<h1 style={{fontFamily:F.sans,fontSize:"clamp(56px,10vw,140px)",fontWeight:900,lineHeight:0.85,letterSpacing:"-0.04em",color:C.cream,opacity:loaded?1:0,transform:loaded?"translateY(0)":"translateY(44px)",transition:"all 1.1s cubic-bezier(0.16,1,0.3,1) 0.5s"}}>PRON<br/><span style={{color:C.red}}>TO.</span></h1>
<p style={{fontFamily:F.sans,fontSize:"clamp(14px,1.2vw,17px)",lineHeight:1.85,color:C.muted,maxWidth:"520px",marginTop:"28px",opacity:loaded?1:0,transition:"opacity 0.9s ease 0.9s"}}>Five bold flavors. Zero sugar. No crash. Fuel for the ones who move first — from the gym floor to the festival ground.</p>
<div style={{display:"flex",gap:"16px",marginTop:"44px",opacity:loaded?1:0,transition:"opacity 0.9s ease 1.2s",flexWrap:"wrap"}}>
<button style={{fontFamily:F.sans,fontSize:"10px",fontWeight:700,letterSpacing:"0.15em",textTransform:"uppercase",color:C.cream,background:`linear-gradient(135deg,${C.red},${C.redDeep})`,border:"none",padding:"15px 44px",cursor:"pointer",transition:"all 0.3s"}} onMouseEnter={e=>e.currentTarget.style.transform="translateY(-2px)"} onMouseLeave={e=>e.currentTarget.style.transform="translateY(0)"}>Shop Now</button>
<button style={{fontFamily:F.sans,fontSize:"10px",fontWeight:500,letterSpacing:"0.15em",textTransform:"uppercase",color:C.cream,background:"transparent",border:`1px solid ${C.border}`,padding:"15px 38px",cursor:"pointer",transition:"all 0.3s"}} onMouseEnter={e=>{e.currentTarget.style.borderColor=C.red;e.currentTarget.style.color=C.red}} onMouseLeave={e=>{e.currentTarget.style.borderColor=C.border;e.currentTarget.style.color=C.cream}}>Wholesale Inquiry</button></div></div></section>)}

function Products(){const[hover,setHover]=useState<number|null>(null);const products=[{name:"Blue Vanilla Ice",img:"/images/products/blue-vanilla-ice.png",desc:"Cool. Smooth. Unstoppable. Vanilla ice meets arctic blue for a crisp clean finish.",price:"$3.99",accent:C.blue},{name:"Dragonfruit",img:"/images/products/dragonfruit.png",desc:"Bold heat. Tropical fire. Exotic dragonfruit with a slow-burn energy that sustains.",price:"$3.99",accent:"#c83020"},{name:"Matcha",img:"/images/products/matcha.png",desc:"Zen focus. Clean power. Japanese matcha meets premium energy for balanced output.",price:"$3.99",accent:C.greenBright},{name:"Original",img:"/images/products/original.png",desc:"The flagship. Pure lightning in a can. 200mg clean caffeine, zero compromise.",price:"$3.99",accent:C.yellow},{name:"Strawburst",img:"/images/products/strawburst.png",desc:"Sweet explosion. Bold strawberry with a rocket-fuel kick that hits different.",price:"$3.99",accent:C.pink}];return(
<section id="flavors" style={{background:C.base,padding:"120px clamp(32px,6vw,96px)"}}><div style={{maxWidth:"1400px",margin:"0 auto"}}><Reveal><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",flexWrap:"wrap",gap:"24px",marginBottom:"64px"}}><div><div style={{fontFamily:F.sans,fontSize:"9px",letterSpacing:"0.48em",textTransform:"uppercase",color:C.red,marginBottom:"16px"}}>5 Bold Flavors</div><h2 style={{fontFamily:F.sans,fontSize:"clamp(36px,5vw,72px)",fontWeight:900,lineHeight:0.9,letterSpacing:"-0.04em",color:C.cream}}>Pick Your<br/>Power.</h2></div><p style={{fontFamily:F.sans,fontSize:"15px",lineHeight:1.8,color:C.muted,maxWidth:"380px"}}>Each flavor is its own universe. Same clean formula. Same zero sugar. Different energy.</p></div></Reveal>
<div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:"2px",background:C.border}}>{products.map((p,i)=>(<div key={p.name} onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(null)} style={{background:hover===i?C.surface:C.base,padding:"32px 20px",cursor:"pointer",transition:"background 0.3s",position:"relative",overflow:"hidden"}}>{hover===i&&<div style={{position:"absolute",inset:0,background:`radial-gradient(circle at 50% 30%,${p.accent}18,transparent 70%)`}}/>}<div style={{position:"absolute",top:0,left:0,right:0,height:"2px",background:hover===i?p.accent:"transparent",transition:"background 0.3s"}}/><div style={{position:"relative",zIndex:1}}><div style={{width:"100%",aspectRatio:"3/4",marginBottom:"20px",display:"flex",alignItems:"center",justifyContent:"center",overflow:"hidden"}}><img src={p.img} alt={p.name} style={{width:"100%",height:"100%",objectFit:"contain",transform:hover===i?"scale(1.05)":"scale(1)",transition:"transform 0.5s cubic-bezier(0.16,1,0.3,1)"}}/></div><div style={{fontFamily:F.sans,fontSize:"8px",fontWeight:600,letterSpacing:"0.38em",textTransform:"uppercase",color:p.accent,marginBottom:"8px"}}>Pronto</div><div style={{fontFamily:F.sans,fontSize:"18px",fontWeight:800,letterSpacing:"-0.02em",color:C.cream,marginBottom:"10px"}}>{p.name}</div><p style={{fontFamily:F.sans,fontSize:"12px",lineHeight:1.7,color:C.muted,marginBottom:"20px"}}>{p.desc}</p><div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{fontFamily:F.sans,fontSize:"18px",fontWeight:800,color:p.accent}}>{p.price}</div><button style={{fontFamily:F.sans,fontSize:"8px",fontWeight:600,letterSpacing:"0.2em",textTransform:"uppercase",color:p.accent,background:"transparent",border:`1px solid ${p.accent}30`,padding:"7px 14px",cursor:"pointer",transition:"all 0.3s",opacity:hover===i?1:0}}>Buy →</button></div></div></div>))}</div>
<Reveal d={0.2}><div style={{marginTop:"48px",position:"relative",overflow:"hidden"}}><img src="/images/products/all-flavors-lineup.png" alt="Pronto Energy Complete Lineup" style={{width:"100%",height:"auto",display:"block"}}/><div style={{position:"absolute",inset:0,background:`linear-gradient(90deg,${C.base}cc 0%,transparent 30%,transparent 70%,${C.base}cc 100%)`}}/></div></Reveal></div></section>)}

function Lifestyle(){const images=[{src:"/images/lifestyle/cheers-boat-sunset.png",label:"Golden Hour"},{src:"/images/lifestyle/festival-girl-dragonfruit.png",label:"Festival Season"},{src:"/images/lifestyle/gym-girl-blue-vanilla.png",label:"Performance"},{src:"/images/lifestyle/stadium-fans-game-day.png",label:"Game Day"},{src:"/images/lifestyle/beach-girls-sunset.png",label:"Beach Vibes"},{src:"/images/lifestyle/festival-night-crew.png",label:"Night Energy"}];return(
<section id="lifestyle" style={{background:C.surface,padding:"120px 0",position:"relative",overflow:"hidden"}}><Grain o={0.03}/><div style={{padding:"0 clamp(32px,6vw,96px)",maxWidth:"1400px",margin:"0 auto 64px"}}><Reveal><div style={{fontFamily:F.sans,fontSize:"9px",letterSpacing:"0.48em",textTransform:"uppercase",color:C.red,marginBottom:"16px"}}>The Pronto Life</div><h2 style={{fontFamily:F.sans,fontSize:"clamp(32px,4.5vw,64px)",fontWeight:900,lineHeight:0.9,letterSpacing:"-0.04em",color:C.cream}}>Wherever You<br/><span style={{color:C.red}}>Go.</span></h2></Reveal></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:"3px",padding:"0 3px"}}>{images.map((img,i)=>(<div key={i} style={{position:"relative",overflow:"hidden",aspectRatio:i===0||i===3?"16/10":"3/4"}}><img src={img.src} alt={img.label} loading="lazy" style={{width:"100%",height:"100%",objectFit:"cover",transition:"transform 0.8s cubic-bezier(0.16,1,0.3,1)"}} onMouseEnter={e=>e.currentTarget.style.transform="scale(1.04)"} onMouseLeave={e=>e.currentTarget.style.transform="scale(1)"}/><div style={{position:"absolute",bottom:0,left:0,right:0,padding:"40px 24px 20px",background:"linear-gradient(transparent,rgba(0,0,0,0.7))"}}><div style={{fontFamily:F.sans,fontSize:"8px",fontWeight:600,letterSpacing:"0.4em",textTransform:"uppercase",color:C.red}}>{img.label}</div></div></div>))}</div></section>)}

function TheScience(){const facts=[{label:"Caffeine Source",value:"Natural · Green Tea Extract",color:C.greenBright},{label:"Crash Prevention",value:"Extended-Release Formula",color:C.red},{label:"Amino Profile",value:"L-Theanine + L-Citrulline",color:C.greenBright},{label:"B-Vitamin Stack",value:"B3 · B6 · B12 Complex",color:C.red},{label:"Sugar Content",value:"Zero — All Variants",color:C.greenBright},{label:"Certification",value:"NSF Certified · Clean Label",color:C.red}];return(
<section id="science" style={{background:C.base,padding:"120px clamp(32px,6vw,96px)",position:"relative",overflow:"hidden"}}><Grain o={0.03}/><div style={{maxWidth:"1400px",margin:"0 auto",position:"relative",zIndex:1}}><Reveal><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"80px",alignItems:"center"}}><div><div style={{fontFamily:F.sans,fontSize:"9px",letterSpacing:"0.48em",textTransform:"uppercase",color:C.red,marginBottom:"16px"}}>The Formula</div><h2 style={{fontFamily:F.sans,fontSize:"clamp(32px,4.5vw,64px)",fontWeight:900,lineHeight:0.9,letterSpacing:"-0.04em",color:C.cream,marginBottom:"24px"}}>Built Different.<br/><span style={{color:C.red}}>By Design.</span></h2><p style={{fontFamily:F.sans,fontSize:"15px",lineHeight:1.85,color:C.muted,marginBottom:"40px"}}>Every ingredient earns its spot. No proprietary blends. No artificial dyes. Just clean science at effective doses.</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"2px",background:C.border}}>{facts.map(f=>(<div key={f.label} style={{background:C.surface,padding:"24px 20px"}}><div style={{fontFamily:F.sans,fontSize:"8px",fontWeight:600,letterSpacing:"0.35em",textTransform:"uppercase",color:f.color,marginBottom:"8px"}}>{f.label}</div><div style={{fontFamily:F.sans,fontSize:"13px",fontWeight:600,color:C.cream,lineHeight:1.4}}>{f.value}</div></div>))}</div></div><div style={{position:"relative"}}><img src="/images/products/lab-schematic.png" alt="Pronto Pilot Schematic" style={{width:"100%",height:"auto"}}/><div style={{position:"absolute",inset:0,background:`linear-gradient(180deg,transparent 60%,${C.base} 100%)`}}/></div></div></Reveal></div></section>)}

function RetailWholesale(){const channels=[{title:"Direct to Consumer",desc:"Order Pronto directly. Bundles, subscriptions, and single-unit purchases.",cta:"Shop Now"},{title:"Retail Placement",desc:"Grocery, convenience, and specialty retail partnerships available.",cta:"Retail Inquiry"},{title:"Hospitality & Events",desc:"Supply Pronto to hotels, venues, gyms, stadiums, and corporate events.",cta:"Venue Supply"},{title:"Wholesale Distribution",desc:"Regional and national distribution partnerships for volume operators.",cta:"Distributor Inquiry"}];return(
<section id="partners" style={{background:C.surface,padding:"120px clamp(32px,6vw,96px)"}}><div style={{maxWidth:"1400px",margin:"0 auto"}}><Reveal><div style={{fontFamily:F.sans,fontSize:"9px",letterSpacing:"0.48em",textTransform:"uppercase",color:C.red,marginBottom:"16px"}}>Distribution</div><h2 style={{fontFamily:F.sans,fontSize:"clamp(32px,4.5vw,64px)",fontWeight:900,lineHeight:0.9,letterSpacing:"-0.04em",color:C.cream,marginBottom:"64px"}}>Find Pronto<br/>Everywhere.</h2></Reveal><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:"2px",background:C.border}}>{channels.map((ch,i)=>(<div key={ch.title} style={{background:C.base,padding:"52px 44px",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,left:0,bottom:0,width:"2px",background:`linear-gradient(180deg,${C.red},${C.green})`}}/><div style={{paddingLeft:"28px"}}><div style={{fontFamily:F.sans,fontSize:"9px",fontWeight:600,letterSpacing:"0.38em",textTransform:"uppercase",color:C.red,marginBottom:"16px"}}>0{i+1}</div><div style={{fontFamily:F.sans,fontSize:"26px",fontWeight:800,letterSpacing:"-0.02em",color:C.cream,marginBottom:"14px"}}>{ch.title}</div><p style={{fontFamily:F.sans,fontSize:"14px",lineHeight:1.75,color:C.muted,marginBottom:"28px"}}>{ch.desc}</p><button style={{fontFamily:F.sans,fontSize:"9px",fontWeight:600,letterSpacing:"0.25em",textTransform:"uppercase",color:C.red,background:"transparent",border:`1px solid ${C.red}30`,padding:"10px 24px",cursor:"pointer",transition:"all 0.3s"}}>{ch.cta} →</button></div></div>))}</div></div></section>)}

function ClosingCTA(){return(<section style={{background:C.base,padding:"160px clamp(32px,6vw,96px)",position:"relative",overflow:"hidden"}}><Grain o={0.04}/><div style={{position:"absolute",inset:0,background:`radial-gradient(ellipse at 60% 50%,${C.redGlow},transparent 60%),radial-gradient(ellipse at 30% 50%,${C.greenGlow},transparent 60%)`}}/><div style={{maxWidth:"860px",margin:"0 auto",textAlign:"center",position:"relative",zIndex:2}}><Reveal><div style={{fontFamily:F.sans,fontSize:"9px",letterSpacing:"0.55em",textTransform:"uppercase",color:C.red,marginBottom:"28px"}}>No Crash. No Excuse.</div><h2 style={{fontFamily:F.sans,fontSize:"clamp(40px,7vw,96px)",fontWeight:900,lineHeight:0.87,letterSpacing:"-0.04em",color:C.cream,marginBottom:"28px"}}>GO.<br/><span style={{color:C.red}}>PRONTO.</span></h2><p style={{fontFamily:F.sans,fontSize:"16px",lineHeight:1.85,color:C.muted,maxWidth:"480px",margin:"0 auto 52px"}}>Five flavors. Zero sugar. Clean energy for the operators, the creators, and the ones who will not accept a compromise.</p><div style={{display:"flex",gap:"16px",justifyContent:"center",flexWrap:"wrap"}}><button style={{fontFamily:F.sans,fontSize:"10px",fontWeight:700,letterSpacing:"0.15em",textTransform:"uppercase",color:C.cream,background:`linear-gradient(135deg,${C.red},${C.redDeep})`,border:"none",padding:"16px 52px",cursor:"pointer",transition:"all 0.3s"}} onMouseEnter={e=>e.currentTarget.style.transform="translateY(-2px)"} onMouseLeave={e=>e.currentTarget.style.transform="translateY(0)"}>Shop Pronto</button><button style={{fontFamily:F.sans,fontSize:"10px",fontWeight:500,letterSpacing:"0.15em",textTransform:"uppercase",color:C.cream,background:"transparent",border:`1px solid ${C.border}`,padding:"16px 40px",cursor:"pointer",transition:"all 0.3s"}} onMouseEnter={e=>{e.currentTarget.style.borderColor=C.red;e.currentTarget.style.color=C.red}} onMouseLeave={e=>{e.currentTarget.style.borderColor=C.border;e.currentTarget.style.color=C.cream}}>Wholesale Inquiry</button></div></Reveal></div></section>)}

function Footer(){return(<footer style={{background:C.deep,borderTop:`1px solid ${C.border}`,padding:"64px clamp(32px,6vw,96px) 40px"}}><div style={{maxWidth:"1400px",margin:"0 auto"}}><div style={{display:"grid",gridTemplateColumns:"1.5fr repeat(3,1fr)",gap:"48px",marginBottom:"64px"}}><div><div style={{display:"flex",alignItems:"center",gap:"8px",marginBottom:"16px"}}><div style={{width:"6px",height:"24px",background:`linear-gradient(180deg,${C.red},${C.green})`,borderRadius:"3px"}}/><span style={{fontFamily:F.sans,fontSize:"20px",fontWeight:900,color:C.cream,letterSpacing:"0.06em"}}>PRONTO</span></div><p style={{fontFamily:F.sans,fontSize:"13px",lineHeight:1.7,color:C.muted}}>Premium energy for performers. No crash. No compromise.</p></div>{[{h:"Flavors",l:["Blue Vanilla Ice","Dragonfruit","Matcha","Original","Strawburst","White Pineapple"]},{h:"Business",l:["Wholesale Inquiry","Retail Placement","Hospitality Supply","Distributor Program","Brand Partnerships"]},{h:"Company",l:["About Pronto","The Science","Certifications","Media & Press","A KHG Brand"]}].map(col=>(<div key={col.h}><div style={{fontFamily:F.sans,fontSize:"8px",fontWeight:600,letterSpacing:"0.4em",textTransform:"uppercase",color:C.red,marginBottom:"20px"}}>{col.h}</div><ul style={{listStyle:"none",padding:0,margin:0,display:"flex",flexDirection:"column",gap:"10px"}}>{col.l.map(item=><li key={item} style={{fontFamily:F.sans,fontSize:"13px",color:C.muted,cursor:"pointer"}}>{item}</li>)}</ul></div>))}</div><div style={{borderTop:`1px solid ${C.border}`,paddingTop:"24px",display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:"16px"}}><div style={{fontFamily:F.sans,fontSize:"11px",color:"rgba(255,255,255,0.2)"}}>© 2026 Pronto Energy. A KHG Brand. All rights reserved.</div><div style={{display:"flex",gap:"24px"}}>{["Privacy","Terms","Contact"].map(i=><span key={i} style={{fontFamily:F.sans,fontSize:"11px",color:"rgba(255,255,255,0.22)",cursor:"pointer"}}>{i}</span>)}</div></div></div></footer>)}

export default function ProntoEnergyV3(){const[portalDone,setPortalDone]=useState(false);const handlePortalComplete=useCallback(()=>setPortalDone(true),[]);return(<div style={{background:C.base}}>{!portalDone&&<VideoPortal onComplete={handlePortalComplete}/>}<Nav visible={portalDone}/><Hero siteReady={portalDone}/><Products/><Lifestyle/><TheScience/><RetailWholesale/><ClosingCTA/><Footer/></div>)}
