"use client";
import {useEffect,useState} from "react";
const CAP="https://wfkohcwxxsrhcxhepfql.supabase.co/functions/v1/marketing-event-capture",KEY="pronto-energy:pwa-dismissed",WEEK=604800000;
const get=(k:string)=>{try{return localStorage.getItem(k)}catch{return null}},put=(k:string,v:string)=>{try{localStorage.setItem(k,v)}catch{}};
const ios=()=>/iphone|ipad|ipod/i.test(navigator.userAgent)||(navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1);
const standalone=()=>matchMedia("(display-mode: standalone)").matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone);
function visitor(){let v=get("khg_vid");if(v)return v;v=crypto.randomUUID();put("khg_vid",v);return v}
function track(event_type:string,metadata:Record<string,string>={}){fetch(CAP,{method:"POST",keepalive:true,headers:{"content-type":"application/json"},body:JSON.stringify({brand_key:"pronto-energy",event_type,visitor_key:visitor(),metadata:{event_id:crypto.randomUUID(),app:"pronto-energy",path:(location.pathname+location.search).slice(0,500),...metadata}})}).catch(()=>{})}
export default function InstallAppPrompt(){
 const[prompt,setPrompt]=useState<any>(null),[show,setShow]=useState(false),[steps,setSteps]=useState(false),[apple,setApple]=useState(false);
 useEffect(()=>{if(standalone())return;const a=ios();setApple(a);if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});const d=Number(get(KEY)||0),eligible=!d||Date.now()-d>WEEK;const before=(e:any)=>{e.preventDefault();setPrompt(e);if(eligible)setTimeout(()=>setShow(true),1800)},done=()=>{setShow(false);track("app_install",{platform:a?"ios":"web",variant:"pronto_pwa"})};addEventListener("beforeinstallprompt",before);addEventListener("appinstalled",done);let t=0;if(eligible&&a)t=window.setTimeout(()=>setShow(true),4800);return()=>{removeEventListener("beforeinstallprompt",before);removeEventListener("appinstalled",done);if(t)clearTimeout(t)}},[]);
 if(!show)return null;
 const close=()=>{put(KEY,String(Date.now()));setShow(false);track("cta_click",{cta:"pwa_prompt_dismiss"})};
 const install=async()=>{track("app_install_click",{platform:apple?"ios":"web",variant:prompt?"native_prompt":"instructions"});if(prompt){const r=await prompt.prompt();setPrompt(null);if(r.outcome==="accepted")setShow(false);return}setSteps(true)};
 return <div className="pr-pwa"><section><button className="x" onClick={close}>×</button><img className="logo" src="/images/pronto-logo.png" alt="Pronto Energy"/>{!steps?<><div className="k">ENERGY / ONE TAP AWAY</div><h2>KEEP<br/><em>PRONTO</em><br/>ON DECK.</h2><p>Flavors, drops, retail, events and Pronto Energy updates — directly from your Home Screen.</p><button className="go" onClick={install}>{prompt?"INSTALL PRONTO":"ADD PRONTO"}</button><button className="later" onClick={close}>Keep moving</button></>:<><div className="k">{apple?"IPHONE / HOME SCREEN":"INSTALL / HOME SCREEN"}</div><h2>THREE TAPS.<br/><em>MOVE FIRST.</em></h2><p>1. {apple?"Tap Share in Safari":"Open the browser menu"}<br/>2. Choose Add to Home Screen / Install App<br/>3. Tap Add</p><button className="go" onClick={close}>GOT IT</button></>}<style jsx>{`.pr-pwa{position:fixed;inset:0;z-index:2147483000;display:grid;place-items:end center;padding:16px;background:#05070bdd;backdrop-filter:blur(12px)}section{position:relative;width:min(650px,100%);padding:34px 24px 22px;border:1px solid #ff5a2e66;border-radius:28px;background:radial-gradient(circle at 88% 4%,#057cff38,transparent 31%),radial-gradient(circle at 70% 12%,#ff5a2e2b,transparent 28%),linear-gradient(145deg,#101722,#05070b 72%);color:#fff;box-shadow:0 35px 100px #000d}.x{position:absolute;right:13px;top:13px;width:38px;height:38px;border-radius:50%;border:1px solid #fff2;background:#fff1;color:#fff;font-size:24px}.logo{width:160px;height:62px;object-fit:contain;object-position:left center;margin-bottom:20px}.k{color:#ff7a42;font:900 9px Arial;letter-spacing:.2em}.pr-pwa h2{font:900 clamp(36px,9vw,60px)/.84 Arial;margin:12px 0;letter-spacing:-.06em}.pr-pwa h2 em{font-style:normal;color:#4ea4ff}.pr-pwa p{max-width:470px;color:#c7ccd2;font:500 14px/1.6 Arial}.go{width:100%;min-height:56px;border:0;border-radius:14px;background:linear-gradient(90deg,#ff6a38,#ff8d35);color:#0b0705;font:900 12px Arial;letter-spacing:.08em}.later{width:100%;border:0;background:none;color:#8b939d;padding:13px;font:700 11px Arial}@media(min-width:700px){.pr-pwa{place-items:center}}`}</style></section></div>
}